### ISSUE TITLE
It seems that gatsby-plugin-scroll-reveal isn't compatible with version3.0 Gatsby.js

### ISSUE THREAD

**Issue by xnslx** [solublestudio/gatsby-plugin-scroll-reveal#17]
I am trying to install ```gatsby-plugin-scroll-reveal``` to my Gatsby application. My Gatsby version is ```"gatsby": "^3.5.0"```. It seems that it isn't compatible with this version of Gatsby? Can I know how to fix it?

**Comment by bacxhus** [comment]
Doesn't seem to be working at all for me either.

**Comment by Endorel** [comment]
There is a PR active that will hopefully fix this, it just needs to get approved and merged.

**Comment by xnslx** [comment]
@Endorel Hey, thank you for letting me know!

**Comment by mikekok** [comment]
Still not compatible.
