### ISSUE TITLE
sal animations don't work alongside react-window

### ISSUE THREAD

**Issue by smoke-indica** [solublestudio/gatsby-plugin-scroll-reveal#2]
When I use this plugin alongside [react-window](https://www.npmjs.com/package/react-window), elements stop rendering and the solution appears to be to disable animations.

Great plugin by the way 👍

**Comment by solubletech** [comment]
Oh! Sorry for the late response.
This plugin checks all `data-sal` attributes on page load. In react-window items are rendered later, but sure you can find a callback on each row appear in react-window to add a class with the right transition! :)
