### ISSUE TITLE
Plugin does not work together with gatsby-plugin-transition-link

### ISSUE THREAD

**Issue by Reinards** [solublestudio/gatsby-plugin-scroll-reveal#5]
Hey! I appreciate the plugin you have created, but there is some issue which I cannot solve for myself and thought that maybe there is a problem in the code of yours.

I am developing a static website using Gatsby and I have these two plugins:
* gatsby-plugin-scroll-reveal
* gatsby-plugin-transition-link

Separately each plugin works just fine, but scroll reveal stops working after a transition to another page. It does work when I reload the page manually but not after there has been a transition.

I am not using any crazy configuration,, it is a very basic site. This is the second project I have seen this issue with.

Maybe there is some project configuration I must make for these plugins to work together?

Thank you a lot!

**Comment by solubletech** [comment]
Hi @Reinards, gatsby-plugin-transition-link generate a wrapper of your main page. That's could be a reason why scroll-reveal don't work properly.

**Comment by Reinards** [comment]
Hey @solubletech , thank you. Is there anything I can do about it without editing the source code of these plugins?

**Comment by solubletech** [comment]
Hey @Reinards , can be because you are adding `gatsby-plugin-transition-link` before in the config. Assure that `gatsby-plugin-scroll-reveal` loads first!
